export interface BusRoute {
  Description: string;
  IsRunning: false;
  MapLineColor: string;
  RouteID: number;
  Stops: BusRouteStop[];
  [key: string]: unknown;
  /** The time it takes for one bus to circle the route. Manually added based on schedule */
  _RouteTime: number;
}

export interface BusRouteStop {
  RouteID: number;
  RouteStopID: number;
  SignVerbiage: string;
  Latitude: number;
  Longitude: number;
  [key: string]: unknown;
}

export const routes: BusRoute[] = [
  {
    _RouteTime: 25,
    Description: "A Line",
    ETATypeID: 1,
    EncodedPolyline:
      "gcklEzqfnUYh@KRw@vAKNMRWZMNSTSRUTA?QNSNWN]PKDQH??I_@CIGUI[I][u@MY]k@EIQUKOMOIISUWSMIKI[SIGSMYSCCOMMOYa@S[U_@a@q@??n@o@|AgB|@gALMFK`@m@FKR]P]Ti@JWDKBKFQDMFODSFSJ_@He@Ji@D[BUD]BU@W@IDg@?C@_@@[?C?CGWAgBAMCy@C[E_@Im@Im@E[CMGY@[?AAAGWOc@I]Ma@??NGh@YFEv@_@bAYBEBAZIDCbASbAUn@MD?f@IHAl@MBAVDTG`@KTELCFCRE`@I??PC\\IDCpDw@??EQG]?EEWCOEUGSEKIQAEQYU[??KOCEWe@Oa@Qk@ACESCQCQCSCUAECo@?W?W@S@Q@M@OBUBMBODQH[DM?KLUL[LUPWRWLMLMPOJGHGPKXOr@]BEx@a@??`@QVMB?VK`@MPIJ@B?z@Q??@?t@IPCLAj@GNEj@E\\CV?JANA\\@H???L@V@jAJLBNB^FRDh@JF@XFb@HL@LB`AXp@T^P~Ap@dAn@RPTR??TPZd@BFP`@DNBLFXDp@A@A??@A@?@A??@?@A??@?@?@?@?@?@?@?@?@?@@??@?@@??@@@@@@@@??@@?@?@?@?@?@?@?@A@??A@?@A@A?A@A?A?A@??A?A?A?A?A?A?A?AAA?AAA?AAAAAA??AA?AAA?A?A?A?A?A?A??@A???Eq@GYCMEOQa@CG[e@k@e@SQeAo@_Bq@_@Qg@Q??ICaAYMCMAc@IYGGAi@KSE_@GOCMC??@UBWB[BM@CFQ?CTk@`@gAFSBI@K@?@SDi@Bi@??@YaAGC?OAc@A]AQ?Q?c@?c@?_@@[@_@@YBG@_@B_@DWB_@FI@WDSDs@L?@QBYHWHWH]JWHC@g@RWJSHC@MFaBv@_@RA?qAn@q@Z{@^{@`@{BbAWJy@^w@\\??ULF^Fd@Fh@@BNnANbA@NLx@BPZdCF`@d@rDBNb@dD@FJ~@BL@H\\fCBTBFh@bEFh@Ff@BRBLDf@Jz@Jx@@BFh@??RtAb@|C@NJl@Fh@@H?@@@@JDp@BRDj@AX?f@?h@?b@Af@An@C^E^Ix@EZADG\\Mn@EPMh@Md@KZIRIVKXS`@MVEJ_@n@]n@IPKNABKPEJKP",
    GtfsId: "",
    HideRouteLine: false,
    InfoText: "",
    IsCheckLineOnlyOnMap: false,
    IsCheckedOnMap: false,
    IsRunning: false,
    IsVisibleOnMap: true,
    Landmarks: [],
    MapLatitude: 33.6430932897,
    MapLineColor: "#FBF140",
    MapLongitude: -117.8290403336,
    MapZoom: 15,
    Order: 15,
    RouteID: 7,
    RouteVehicleIcon: "",
    ShowPolygon: false,
    ShowRouteArrows: true,
    StopTimesPDFLink: "",
    Stops: [
      {
        AddressID: 8,
        City: "",
        Latitude: 33.6493403817,
        Line1: "University Center, North",
        Line2: "",
        Longitude: -117.8397880032,
        State: "",
        Zip: "",
        Description: "University Center, North (107)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 10,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 49,
        SecondsAtStop: 0,
        SecondsToNextStop: 296,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "University Center, North",
        TextingKey: "107",
      },
      {
        AddressID: 17,
        City: "",
        Latitude: 33.6481349538,
        Line1: "Campus - California",
        Line2: "",
        Longitude: -117.8300087013,
        State: "",
        Zip: "",
        Description: "Campus - California (108)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 20,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 50,
        SecondsAtStop: 0,
        SecondsToNextStop: 53,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Campus - California",
        TextingKey: "108",
      },
      {
        AddressID: 1,
        City: "",
        Latitude: 33.6474334519,
        Line1: "AV Stop #1",
        Line2: "",
        Longitude: -117.8284007156,
        State: "",
        Zip: "",
        Description: "AV Stop #1 (109)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 30,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 51,
        SecondsAtStop: 0,
        SecondsToNextStop: 76,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "AV Stop #1",
        TextingKey: "109",
      },
      {
        AddressID: 2,
        City: "",
        Latitude: 33.6462213807,
        Line1: "CDS Stop #1",
        Line2: "",
        Longitude: -117.8243964871,
        State: "",
        Zip: "",
        Description: "CDS Stop #1 (110)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 40,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 52,
        SecondsAtStop: 0,
        SecondsToNextStop: 24,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "CDS Stop #1",
        TextingKey: "110",
      },
      {
        AddressID: 3,
        City: "",
        Latitude: 33.6451737063,
        Line1: "CDS Stop #2",
        Line2: "",
        Longitude: -117.8240227772,
        State: "",
        Zip: "",
        Description: "CDS Stop #2 (111)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 50,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 53,
        SecondsAtStop: 0,
        SecondsToNextStop: 24,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "CDS Stop #2",
        TextingKey: "111",
      },
      {
        AddressID: 4,
        City: "",
        Latitude: 33.6436172412,
        Line1: "CDS Stop #3",
        Line2: "",
        Longitude: -117.8238082448,
        State: "",
        Zip: "",
        Description: "CDS Stop #3 (112)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 60,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 54,
        SecondsAtStop: 0,
        SecondsToNextStop: 57,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "CDS Stop #3",
        TextingKey: "112",
      },
      {
        AddressID: 5,
        City: "",
        Latitude: 33.6401233106,
        Line1: "631 VDC Stop #1",
        Line2: "",
        Longitude: -117.8250966635,
        State: "",
        Zip: "",
        Description: "631 VDC Stop #1 (103)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 70,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 55,
        SecondsAtStop: 0,
        SecondsToNextStop: 112,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "631 VDC Stop #1",
        TextingKey: "103",
      },
      {
        AddressID: 6,
        City: "",
        Latitude: 33.641542267,
        Line1: "621 VDC Stop #2",
        Line2: "",
        Longitude: -117.8242361073,
        State: "",
        Zip: "",
        Description: "621 VDC Stop #2 (104)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 80,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 56,
        SecondsAtStop: 0,
        SecondsToNextStop: 267,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "621 VDC Stop #2",
        TextingKey: "104",
      },
      {
        AddressID: 7,
        City: "",
        Latitude: 33.6484168835,
        Line1: "Puerta del Sol, North",
        Line2: "",
        Longitude: -117.8328279894,
        State: "",
        Zip: "",
        Description: "Puerta del Sol, North (113)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 90,
        RouteDescription: "",
        RouteID: 7,
        RouteStopID: 57,
        SecondsAtStop: 0,
        SecondsToNextStop: 94,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Puerta del Sol, North",
        TextingKey: "113",
      },
    ],
    TextingKey: "",
    UseScheduleTripsInPassengerCounter: false,
    VehicleMarkerCssClass: "",
  },
  {
    _RouteTime: 20,
    Description: "E Line",
    ETATypeID: 1,
    EncodedPolyline:
      "sbklEfrfnUHMHO@CFMXg@LUR_@NYJQHQDGFON[Pe@Pg@DQL_@BKDMDQF[Hc@Ha@BUD[Fi@Dg@@]@GBi@?W@Q?u@?e@?[CYAYAUMyAIo@a@yCAWSaB_@iC??M_Am@uE]mCCUCSKu@??S_BCQUeBGg@Ig@YuBg@{DAIYwBCOE]i@_EGm@??Ga@ULqAn@gB|@wBfAULkAn@kExBkB~@??MHH\\f@vAHVJ`@Rv@Lj@XpAJh@FRFPNh@Lb@Pb@P`@FHLX@Dh@hAn@rAr@xAP`@L^Lb@Nh@DN@@NNFXBLDZHl@Hl@D^BZBx@@L@fBILAB?B?FAVAVAZANARCXAHGf@CVKn@Mn@ELEPKb@IVCHEHK\\CFIRKRIRQ\\e@v@Yb@QT[^o@r@e@h@sAzA??OLJRj@bAl@~@FHHJRRHHRNZPBBj@^d@^ZZPRRVVb@NVJXZt@Lh@Pp@FZ??HXRK`@QTKDELITOTQZWPQX]JKDIZe@jAqB\\m@HO",
    GtfsId: "",
    HideRouteLine: false,
    InfoText: "",
    IsCheckLineOnlyOnMap: false,
    IsCheckedOnMap: false,
    IsRunning: false,
    IsVisibleOnMap: true,
    Landmarks: [],
    MapLatitude: 33.6499903756,
    MapLineColor: "#9E4DEF",
    MapLongitude: -117.8303574213,
    MapZoom: 15,
    Order: 25,
    RouteID: 8,
    RouteVehicleIcon: "",
    ShowPolygon: false,
    ShowRouteArrows: true,
    StopTimesPDFLink: "",
    Stops: [
      {
        AddressID: 10,
        City: "",
        Latitude: 33.6491800894,
        Line1: "University Center, South",
        Line2: "",
        Longitude: -117.8399216412,
        State: "",
        Zip: "",
        Description: "University Center, South (100)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 10,
        RouteDescription: "",
        RouteID: 8,
        RouteStopID: 58,
        SecondsAtStop: 0,
        SecondsToNextStop: 94,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "University Center, South",
        TextingKey: "100",
      },
      {
        AddressID: 16,
        City: "",
        Latitude: 33.648255526,
        Line1: "Campus - Cornell",
        Line2: "",
        Longitude: -117.8322368923,
        State: "",
        Zip: "",
        Description: "Campus - Cornell",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 20,
        RouteDescription: "",
        RouteID: 8,
        RouteStopID: 59,
        SecondsAtStop: 0,
        SecondsToNextStop: 38,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Campus - Cornell",
        TextingKey: "",
      },
      {
        AddressID: 9,
        City: "",
        Latitude: 33.648821869,
        Line1: "Plaza Verde Housing - Campus",
        Line2: "",
        Longitude: -117.8296420352,
        State: "",
        Zip: "",
        Description: "Plaza Verde Housing - Campus",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 30,
        RouteDescription: "",
        RouteID: 8,
        RouteStopID: 60,
        SecondsAtStop: 0,
        SecondsToNextStop: 419,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Plaza Verde Housing - Campus",
        TextingKey: "",
      },
    ],
    TextingKey: "",
    UseScheduleTripsInPassengerCounter: false,
    VehicleMarkerCssClass: "",
  },
  {
    _RouteTime: 30,
    Description: "H Line",
    ETATypeID: 1,
    EncodedPolyline:
      "sbklEfrfnUHMHO@CFMXg@LUR_@NYJQHQDGFON[Pe@Pg@DQL_@BKDMDQF[Hc@Ha@BUD[Fi@Dg@@]@GBi@?W@Q?u@?e@?[CYAYAUMyAIo@a@yCAWSaB_@iC??M_Am@uE]mC??`@KTELCFCRE`@I??PC\\IDCpDw@??EQG]?EEWCOEUGSEKIQAEQYU[??KOCEWe@Oa@Qk@ACESCQCQCSCUAECo@?W?W@S@Q@M@OBUBMBODQH[DM?KLUL[LUPWRWLMLMPOJGHGPKXOr@]BEx@a@??`@QVMB?VK`@MPIJ@B?z@Q??@?t@IPCLAj@GNEj@E\\CV?JANA\\@H???L@V@jAJLBNB^FRDh@JF@XFb@HL@LB`AXp@T^P~Ap@dAn@RPTR??TPZd@BFP`@DNBLFXDp@A@A??@A@?@A??@?@A??@?@?@?@?@?@?@?@?@?@@??@?@@??@@@@@@@@??@@?@?@?@?@?@?@?@A@??A@?@A@A?A@A?A?A@??A?A?A?A?A?A?A?AAA?AAA?AAAAAA??AA?AAA?A?A?A?A?A?A??@A???Eq@GYCMEOQa@CG[e@k@e@SQeAo@_Bq@_@Qg@Q??ICaAYMCMAc@IYGGAi@KSE_@GOCMCcAI??GAWAWA]AO@K@W?]Bk@DODk@FM@QBu@H}@PC?KAQH_@J??A@WJC?WLa@Py@`@CDs@\\YNQJIFKFQNMLMLSVQVA@??KRMZMT?JELIZEPCNCLCTANALAPAR?V?VBn@@DBTBRBPBPDR@BPj@N`@Vd@BD`@j@PX@DHPDJFRDTBNDV?DF\\??gB\\OBw@Pq@NC@OBc@H[Hs@P??UFBTBFh@bEFh@Ff@BRBLDf@Jz@Jx@@BFh@??RtAb@|C@NJl@Fh@@H?@@@@JDp@BRDj@??aERmBJYAW?Q?O?OAOAYCOCQCICSEg@ISC_@IUESGWE??SCCVKn@Mn@ELEPKb@IVCHEHK\\CFIRKRIRQ\\e@v@Yb@QT[^o@r@e@h@sAzA??OLJRj@bAl@~@FHHJRRHHRNZPBBj@^d@^ZZPRRVVb@NVJXZt@Lh@Pp@FZ??HXRK`@QTKDELITOTQZWPQX]JKDIZe@jAqB\\m@HO",
    GtfsId: "",
    HideRouteLine: false,
    InfoText: "",
    IsCheckLineOnlyOnMap: false,
    IsCheckedOnMap: false,
    IsRunning: false,
    IsVisibleOnMap: true,
    Landmarks: [],
    MapLatitude: 33.6460585986,
    MapLineColor: "#14B3C4",
    MapLongitude: -117.8290832489,
    MapZoom: 15,
    Order: 40,
    RouteID: 4,
    RouteVehicleIcon: "",
    ShowPolygon: false,
    ShowRouteArrows: true,
    StopTimesPDFLink: "",
    Stops: [
      {
        AddressID: 10,
        City: "",
        Latitude: 33.6491800894,
        Line1: "University Center, South",
        Line2: "",
        Longitude: -117.8399216412,
        State: "",
        Zip: "",
        Description: "University Center, South (100)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 10,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 19,
        SecondsAtStop: 0,
        SecondsToNextStop: 94,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "University Center, South",
        TextingKey: "100",
      },
      {
        AddressID: 16,
        City: "",
        Latitude: 33.648255526,
        Line1: "Campus - Cornell",
        Line2: "",
        Longitude: -117.8322368923,
        State: "",
        Zip: "",
        Description: "Campus - Cornell (101)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 20,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 20,
        SecondsAtStop: 0,
        SecondsToNextStop: 47,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Campus - Cornell",
        TextingKey: "101",
      },
      {
        AddressID: 17,
        City: "",
        Latitude: 33.6481349538,
        Line1: "Campus - California",
        Line2: "",
        Longitude: -117.8300087013,
        State: "",
        Zip: "",
        Description: "Campus - California (108)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 30,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 21,
        SecondsAtStop: 0,
        SecondsToNextStop: 53,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Campus - California",
        TextingKey: "108",
      },
      {
        AddressID: 1,
        City: "",
        Latitude: 33.6474334519,
        Line1: "AV Stop #1",
        Line2: "",
        Longitude: -117.8284007156,
        State: "",
        Zip: "",
        Description: "AV Stop #1 (109)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 40,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 22,
        SecondsAtStop: 0,
        SecondsToNextStop: 76,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "AV Stop #1",
        TextingKey: "109",
      },
      {
        AddressID: 2,
        City: "",
        Latitude: 33.6462213807,
        Line1: "CDS Stop #1",
        Line2: "",
        Longitude: -117.8243964871,
        State: "",
        Zip: "",
        Description: "CDS Stop #1 (110)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 50,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 23,
        SecondsAtStop: 0,
        SecondsToNextStop: 24,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "CDS Stop #1",
        TextingKey: "110",
      },
      {
        AddressID: 3,
        City: "",
        Latitude: 33.6451737063,
        Line1: "CDS Stop #2",
        Line2: "",
        Longitude: -117.8240227772,
        State: "",
        Zip: "",
        Description: "CDS Stop #2 (111)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 60,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 24,
        SecondsAtStop: 0,
        SecondsToNextStop: 24,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "CDS Stop #2",
        TextingKey: "111",
      },
      {
        AddressID: 4,
        City: "",
        Latitude: 33.6436172412,
        Line1: "CDS Stop #3",
        Line2: "",
        Longitude: -117.8238082448,
        State: "",
        Zip: "",
        Description: "CDS Stop #3 (112)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 70,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 25,
        SecondsAtStop: 0,
        SecondsToNextStop: 57,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "CDS Stop #3",
        TextingKey: "112",
      },
      {
        AddressID: 5,
        City: "",
        Latitude: 33.6401233106,
        Line1: "631 VDC Stop #1",
        Line2: "",
        Longitude: -117.8250966635,
        State: "",
        Zip: "",
        Description: "631 VDC Stop #1 (103)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 80,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 26,
        SecondsAtStop: 0,
        SecondsToNextStop: 112,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "631 VDC Stop #1",
        TextingKey: "103",
      },
      {
        AddressID: 6,
        City: "",
        Latitude: 33.641542267,
        Line1: "621 VDC Stop #2",
        Line2: "",
        Longitude: -117.8242361073,
        State: "",
        Zip: "",
        Description: "621 VDC Stop #2 (104)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 90,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 27,
        SecondsAtStop: 0,
        SecondsToNextStop: 35,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "621 VDC Stop #2",
        TextingKey: "104",
      },
      {
        AddressID: 12,
        City: "",
        Latitude: 33.6433695334,
        Line1: "VDC Norte Stop #1",
        Line2: "",
        Longitude: -117.823727822,
        State: "",
        Zip: "",
        Description: "VDC Norte Stop #1 (118)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 100,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 28,
        SecondsAtStop: 0,
        SecondsToNextStop: 39,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "VDC Norte Stop #1",
        TextingKey: "118",
      },
      {
        AddressID: 13,
        City: "",
        Latitude: 33.6458222422,
        Line1: "VDC Norte Stop #2",
        Line2: "",
        Longitude: -117.8241054408,
        State: "",
        Zip: "",
        Description: "VDC Norte Stop #2 (124)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 110,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 29,
        SecondsAtStop: 0,
        SecondsToNextStop: 41,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "VDC Norte Stop #2",
        TextingKey: "124",
      },
      {
        AddressID: 14,
        City: "",
        Latitude: 33.6476028622,
        Line1: "VDC Norte Stop #3",
        Line2: "",
        Longitude: -117.8254003689,
        State: "",
        Zip: "",
        Description: "VDC Norte Stop #3 (125)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 120,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 30,
        SecondsAtStop: 0,
        SecondsToNextStop: 168,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "VDC Norte Stop #3",
        TextingKey: "125",
      },
      {
        AddressID: 18,
        City: "",
        Latitude: 33.6472009672,
        Line1: "Plaza Verde Housing - California",
        Line2: "",
        Longitude: -117.8294766414,
        State: "",
        Zip: "",
        Description: "Plaza Verde Housing - California (126)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 120,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 31,
        SecondsAtStop: 0,
        SecondsToNextStop: 0,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Plaza Verde Housing - California",
        TextingKey: "126",
      },
      {
        AddressID: 7,
        City: "",
        Latitude: 33.6484168835,
        Line1: "Puerta del Sol, North",
        Line2: "",
        Longitude: -117.8328279894,
        State: "",
        Zip: "",
        Description: "Puerta del Sol, North (113)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 130,
        RouteDescription: "",
        RouteID: 4,
        RouteStopID: 32,
        SecondsAtStop: 0,
        SecondsToNextStop: 273,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Puerta del Sol, North",
        TextingKey: "113",
      },
    ],
    TextingKey: "",
    UseScheduleTripsInPassengerCounter: false,
    VehicleMarkerCssClass: "",
  },
  {
    _RouteTime: 25,
    Description: "M Line",
    ETATypeID: 1,
    EncodedPolyline:
      "sbklEfrfnUHMHO@CFMXg@LUR_@NYJQHQDGFON[Pe@Pg@DQL_@BKDMDQF[Hc@Ha@BUD[Fi@Dg@@]@GBi@?W@Q?u@?e@?[CYAYAUMyAIo@a@yCAWSaB_@iCM_ACQ??i@cE]mC??`@KTELCFCREr@M\\IDCpDw@REB@@?@?HA??v@Qn@MLCFAx@MVC`@CjAEp@CN?n@@Z@Z@PBN@??d@FZB`@DJ@LBD@d@DJ@LBJBRDLBRHF@f@JHDRD`@DL@N@V@L?J@J@P@l@HdAHT?TB|@H~@HZBr@F^FRBPD??D@\\Jl@V@???M`@Qd@M^KZERCLELGVCNCNGZIb@?BKh@ENI`@I\\[~@EJEJKVm@rAg@fAKXO\\Wf@MTQ\\INW`@e@p@KL]b@OPo@j@KJSPKJSP_@ZEDONIHGB[X??MJHPJ`@FTDRBJ@B@LBV@HBR@`@?^C^C\\Kl@ShA?B?@O`ACZ?R?PAX?Z???R?H@h@Dh@@XD`@BVDVJj@DNH\\F\\BNHl@BV?HDh@BTJjAB\\DVJn@@DJ^LZ@FDJHNVv@DRNt@F^Db@?F@r@@F??@r@?jA@J?N@V@R@L@H?@DZFd@H|@BH@F@NDX@T?@?L?N?XAXCXAP?@?@CLCPCJCJGNCJITOZEHCDKNOTSRMJQNOHQJ]LKDIBG@O@SDk@FKBWFMBYBC?K@Y?WAQ@GAq@?O?O@YAMASCI?KCk@MSGo@UMEUGOEICKCSAQAGAG?C?M?UBC?QDQB??OB[H??AMKq@EUI[IUIOIKOSIKMKEESKYSk@]AASMA?]SUMOM??UMa@YCCYYY_@KMEMEKKOGSGQKa@E[CUCYE{@AUAMEi@CS??CSCQEWAQGc@Ic@EUOi@Qg@EKEICCMUIICGCCMMGGKIIEICWQQU_@Qq@_@ECMIIGQSEGCEGKGKAE?ACGCKGUGU??`@QTKDELITOTQZWPQX]JKDIZe@jAqB\\m@HO",
    GtfsId: "",
    HideRouteLine: false,
    InfoText: "",
    IsCheckLineOnlyOnMap: false,
    IsCheckedOnMap: false,
    IsRunning: false,
    IsVisibleOnMap: true,
    Landmarks: [],
    MapLatitude: 33.6455584332,
    MapLineColor: "#12E32B",
    MapLongitude: -117.8299844711,
    MapZoom: 15,
    Order: 50,
    RouteID: 5,
    RouteVehicleIcon: "",
    ShowPolygon: false,
    ShowRouteArrows: true,
    StopTimesPDFLink: "",
    Stops: [
      {
        AddressID: 10,
        City: "",
        Latitude: 33.6491800894,
        Line1: "University Center, South",
        Line2: "",
        Longitude: -117.8399216412,
        State: "",
        Zip: "",
        Description: "University Center, South (100)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 10,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 33,
        SecondsAtStop: 0,
        SecondsToNextStop: 99,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "University Center, South",
        TextingKey: "100",
      },
      {
        AddressID: 19,
        City: "",
        Latitude: 33.6483527324,
        Line1: "Puerta del Sol, South",
        Line2: "",
        Longitude: -117.8318119335,
        State: "",
        Zip: "",
        Description: "Puerta del Sol, South (137)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 20,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 34,
        SecondsAtStop: 0,
        SecondsToNextStop: 73,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Puerta del Sol, South",
        TextingKey: "137",
      },
      {
        AddressID: 20,
        City: "",
        Latitude: 33.6467912123,
        Line1: "East Campus Housing",
        Line2: "",
        Longitude: -117.8295646227,
        State: "",
        Zip: "",
        Description: "East Campus Housing (158)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 30,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 35,
        SecondsAtStop: 0,
        SecondsToNextStop: 35,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "East Campus Housing",
        TextingKey: "158",
      },
      {
        AddressID: 21,
        City: "",
        Latitude: 33.6441974586,
        Line1: "California - Adobe Circle South",
        Line2: "",
        Longitude: -117.8292835517,
        State: "",
        Zip: "",
        Description: "California - Adobe Circle South (159)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 40,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 36,
        SecondsAtStop: 0,
        SecondsToNextStop: 44,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "California - Adobe Circle South",
        TextingKey: "159",
      },
      {
        AddressID: 22,
        City: "",
        Latitude: 33.6396032773,
        Line1: "Palo Verde",
        Line2: "",
        Longitude: -117.8301865229,
        State: "",
        Zip: "",
        Description: "Palo Verde (160)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 50,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 37,
        SecondsAtStop: 0,
        SecondsToNextStop: 103,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Palo Verde",
        TextingKey: "160",
      },
      {
        AddressID: 23,
        City: "",
        Latitude: 33.642921049,
        Line1: "Engineering",
        Line2: "",
        Longitude: -117.839501316,
        State: "",
        Zip: "",
        Description: "Engineering (161)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 60,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 38,
        SecondsAtStop: 0,
        SecondsToNextStop: 45,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Engineering",
        TextingKey: "161",
      },
      {
        AddressID: 24,
        City: "",
        Latitude: 33.6416719724,
        Line1: "Physical Sciences/MSTB",
        Line2: "",
        Longitude: -117.8447546173,
        State: "",
        Zip: "",
        Description: "Physical Sciences/MSTB (162)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 70,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 39,
        SecondsAtStop: 0,
        SecondsToNextStop: 55,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Physical Sciences/MSTB",
        TextingKey: "162",
      },
      {
        AddressID: 25,
        City: "",
        Latitude: 33.64383063,
        Line1: "West Peltason - Bison",
        Line2: "",
        Longitude: -117.8491363635,
        State: "",
        Zip: "",
        Description: "West Peltason - Bison (163)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 80,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 40,
        SecondsAtStop: 0,
        SecondsToNextStop: 28,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "West Peltason - Bison",
        TextingKey: "163",
      },
      {
        AddressID: 26,
        City: "",
        Latitude: 33.6462897531,
        Line1: "West Peltason - Academy Way",
        Line2: "",
        Longitude: -117.8487750555,
        State: "",
        Zip: "",
        Description: "West Peltason - Academy Way (164)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 90,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 41,
        SecondsAtStop: 0,
        SecondsToNextStop: 26,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "West Peltason - Academy Way",
        TextingKey: "164",
      },
      {
        AddressID: 27,
        City: "",
        Latitude: 33.6479011967,
        Line1: "Bren Events Center - Crawford Hall",
        Line2: "",
        Longitude: -117.8471125842,
        State: "",
        Zip: "",
        Description: "Bren Events Center - Crawford Hall (165)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 100,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 42,
        SecondsAtStop: 0,
        SecondsToNextStop: 31,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Bren Events Center - Crawford Hall",
        TextingKey: "165",
      },
      {
        AddressID: 28,
        City: "",
        Latitude: 33.6489278979,
        Line1: "Humanities & Fine Arts, South",
        Line2: "",
        Longitude: -117.8448493721,
        State: "",
        Zip: "",
        Description: "Humanities & Fine Arts, South (166)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 110,
        RouteDescription: "",
        RouteID: 5,
        RouteStopID: 43,
        SecondsAtStop: 0,
        SecondsToNextStop: 112,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Humanities & Fine Arts, South",
        TextingKey: "166",
      },
    ],
    TextingKey: "",
    UseScheduleTripsInPassengerCounter: false,
    VehicleMarkerCssClass: "",
  },
  {
    _RouteTime: 20,
    Description: "N Line",
    ETATypeID: 1,
    EncodedPolyline:
      "gcklEzqfnUYh@KRw@vAKNMRWZMNSTSRUTA?QNSNWN]PKDQH??I_@CIGUI[I][u@MY]k@EIQUKOMOIISUWSMIKI[SIGSMYSCCOMMOYa@S[U_@a@q@??n@o@|AgB|@gALMFK`@m@FKR]P]Ti@JWDKBKFQDMFODSFSJ_@He@Ji@D[BUD]BU@W@IDg@?C@_@@[?C?CGWAgBAMCy@C[E_@Im@Im@E[CMGY@[?AAAGWOc@I]Ma@Qa@e@cAm@mAQ]i@eAAEO_@GIO_@Oc@Ma@Qi@[gAYoAEUEQI_@U}@COe@uAKQ??`CmAtAs@tBgAjAm@hB}@LIXOf@WZOvAs@TKj@YrBcAzBgA`FaCj@W~@c@v@_@\\Of@SZKx@WdBa@|@OnAO\\Cl@EPAp@Cn@A\\?j@?^@v@DR@r@D??Ch@Eh@ARA?AJCHGRa@fAUj@?BGPABCLCZCVAT??cAI??GAWAWA]AO@K@W?]Bk@DODk@FM@QBu@H}@PC?KAQH_@J??A@WJC?WLa@Py@`@CDs@\\YNQJIFKFQNMLMLSVQVA@??KRMZMT?JELIZEPCNCLCTANALAPAR?V?VBn@@DBTBRBPBPDR@BPj@N`@Vd@BD`@j@PX@DHPDJFRDTBNDV?DF\\??gB\\OBw@Pq@NC@OBc@H[Hs@P??UFBTBFh@bEFh@Ff@BRBLDf@Jz@Jx@@BFh@??RtAb@|C@NJl@Fh@@H?@@@@JDp@BRDj@AX?f@?h@?b@Af@An@C^E^Ix@EZADG\\Mn@EPMh@Md@KZIRIVKXS`@MVEJ_@n@]n@IPKNABKPEJKP",
    GtfsId: "",
    HideRouteLine: false,
    InfoText: "",
    IsCheckLineOnlyOnMap: false,
    IsCheckedOnMap: false,
    IsRunning: false,
    IsVisibleOnMap: true,
    Landmarks: [],
    MapLatitude: 33.6456298856,
    MapLineColor: "#F77A2D",
    MapLongitude: -117.8297698944,
    MapZoom: 15,
    Order: 60,
    RouteID: 6,
    RouteVehicleIcon: "",
    ShowPolygon: false,
    ShowRouteArrows: true,
    StopTimesPDFLink: "",
    Stops: [
      {
        AddressID: 8,
        City: "",
        Latitude: 33.6493403817,
        Line1: "University Center, North",
        Line2: "",
        Longitude: -117.8397880032,
        State: "",
        Zip: "",
        Description: "University Center, North (107)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 10,
        RouteDescription: "",
        RouteID: 6,
        RouteStopID: 44,
        SecondsAtStop: 0,
        SecondsToNextStop: 395,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "University Center, North",
        TextingKey: "107",
      },
      {
        AddressID: 12,
        City: "",
        Latitude: 33.6433695334,
        Line1: "VDC Norte Stop #1",
        Line2: "",
        Longitude: -117.823727822,
        State: "",
        Zip: "",
        Description: "VDC Norte Stop #1 (118)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 20,
        RouteDescription: "",
        RouteID: 6,
        RouteStopID: 48,
        SecondsAtStop: 0,
        SecondsToNextStop: 39,
        ShowDefaultedOnMap: false,
        ShowEstimatesOnMap: false,
        SignVerbiage: "VDC Norte Stop #1",
        TextingKey: "118",
      },
      {
        AddressID: 13,
        City: "",
        Latitude: 33.6458222422,
        Line1: "VDC Norte Stop #2",
        Line2: "",
        Longitude: -117.8241054408,
        State: "",
        Zip: "",
        Description: "VDC Norte Stop #2 (124)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 30,
        RouteDescription: "",
        RouteID: 6,
        RouteStopID: 45,
        SecondsAtStop: 0,
        SecondsToNextStop: 41,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "VDC Norte Stop #2",
        TextingKey: "124",
      },
      {
        AddressID: 14,
        City: "",
        Latitude: 33.6476028622,
        Line1: "VDC Norte Stop #3",
        Line2: "",
        Longitude: -117.8254003689,
        State: "",
        Zip: "",
        Description: "VDC Norte Stop #3 (125)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 40,
        RouteDescription: "",
        RouteID: 6,
        RouteStopID: 46,
        SecondsAtStop: 0,
        SecondsToNextStop: 168,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "VDC Norte Stop #3",
        TextingKey: "125",
      },
      {
        AddressID: 7,
        City: "",
        Latitude: 33.6484168835,
        Line1: "Puerta del Sol, North",
        Line2: "",
        Longitude: -117.8328279894,
        State: "",
        Zip: "",
        Description: "Puerta del Sol, North (113)",
        GtfsId: "",
        Heading: 0,
        MapPoints: [],
        MaxZoomLevel: 16,
        Order: 50,
        RouteDescription: "",
        RouteID: 6,
        RouteStopID: 47,
        SecondsAtStop: 0,
        SecondsToNextStop: 94,
        ShowDefaultedOnMap: true,
        ShowEstimatesOnMap: true,
        SignVerbiage: "Puerta del Sol, North",
        TextingKey: "113",
      },
    ],
    TextingKey: "",
    UseScheduleTripsInPassengerCounter: false,
    VehicleMarkerCssClass: "",
  },
];

export interface ScheduledTime {
  ArrivalTimeUTC: string; // "/Date(1712023200000)/"
  AssignedVehicleId: number;
  Block: string; // "9887954"
  DepartureTimeUTC: string;
}

export interface VehicleEstimate {
  Block: string;
  OnRoute: boolean;
  SecondsToStop: number;
  VehicleID: number;
}

export interface ArrivalStopData {
  RouteDescription: null;
  RouteID: number;
  RouteStopID: number;
  ScheduledTimes: ScheduledTime[];
  ShowDefaultedOnMap: false;
  ShowEstimatesOnMap: false;
  StopDescription: null;
  StopId: number;
  VehicleEstimates: VehicleEstimate[];
}
